# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 16904f769df1d033abe285bb8088218642185c6d3fc9539bd001cd9ea3f6463d79377926cbfaa0a20da762f597c409d6c0e7ef64b945249539284bb74af00f5d

test:
  secret_key_base: 06b1503e38d9ae0551e0ddbe0551eb7a86d1d9903ff8a5b292f763a0b6d68ed998ddad37560108ba9ab3a4e0667a9d15f8030bad276ab3116e4a7a6a60808aa8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
